"""Changed the name of payment methods table

Revision ID: 0fcb7605ee67
Revises: 244b4ee8258e
Create Date: 2024-03-04 10:04:58.395896

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0fcb7605ee67"
down_revision: Union[str, None] = "244b4ee8258e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "payment_type_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_type_id"], ["payment_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.drop_constraint(
        "shop_orders_payment_method_id_fkey", "shop_orders", type_="foreignkey"
    )
    op.drop_table("user_payment_methods")

    op.create_foreign_key(
        None,
        "shop_orders",
        "payment_methods",
        ["payment_method_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shop_orders", type_="foreignkey")
    op.create_foreign_key(
        "shop_orders_payment_method_id_fkey",
        "shop_orders",
        "user_payment_methods",
        ["payment_method_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "user_payment_methods",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "payment_type_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "provider", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "account_number", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expiry_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_default", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["payment_type_id"],
            ["payment_types.id"],
            name="user_payment_methods_payment_type_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="user_payment_methods_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="user_payment_methods_pkey"),
        sa.UniqueConstraint("id", name="user_payment_methods_id_key"),
    )
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
