"""Added payment methods

Revision ID: 1b4a0a6747f4
Revises: f8b3bcc031e9
Create Date: 2024-02-05 20:05:43.781907

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1b4a0a6747f4"
down_revision: Union[str, None] = "f8b3bcc031e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_payment_methods",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "payment_type_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("if_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["payment_type_id"], ["payment_types.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id", "payment_type_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "payment_types", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment_types", type_="unique")
    op.drop_table("user_payment_methods")
    # ### end Alembic commands ###
