"""Added shop order model

Revision ID: 339ee5ad67bc
Revises: cb5396940e04
Create Date: 2024-02-23 08:22:51.289706

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "339ee5ad67bc"
down_revision: Union[str, None] = "cb5396940e04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_orders",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "payment_method_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "shipping_address_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("shipping_method_id", sa.Integer(), nullable=False),
        sa.Column("order_total", sa.Numeric(), nullable=False),
        sa.Column("order_status_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_status_id"], ["order_statuses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["user_payment_methods.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"], ["addresses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shipping_method_id"], ["shipping_methods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shop_orders")
    # ### end Alembic commands ###
