"""Created product cetegory model

Revision ID: 45999034b2a5
Revises: 4f87edf5c884
Create Date: 2024-02-10 16:17:24.322652

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "45999034b2a5"
down_revision: Union[str, None] = "4f87edf5c884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_category_id"],
            ["product_categories.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_categories")
    # ### end Alembic commands ###
