"""Changed name of is_default

Revision ID: 4f87edf5c884
Revises: 1b4a0a6747f4
Create Date: 2024-02-05 20:21:27.958947

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4f87edf5c884"
down_revision: Union[str, None] = "1b4a0a6747f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_payment_methods",
        sa.Column("is_default", sa.Boolean(), nullable=False),
    )
    op.drop_column("user_payment_methods", "if_default")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_payment_methods",
        sa.Column(
            "if_default", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("user_payment_methods", "is_default")
    # ### end Alembic commands ###
