"""Changed the name of shop orders table

Revision ID: 621762139e18
Revises: befe3ebaceee
Create Date: 2024-03-05 12:21:01.535853

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "621762139e18"
down_revision: Union[str, None] = "befe3ebaceee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column(
            "payment_method_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "shipping_address_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("shipping_method_id", sa.Integer(), nullable=False),
        sa.Column("order_total", sa.Numeric(), nullable=False),
        sa.Column("order_status_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_status_id"], ["order_statuses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"], ["payment_methods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"], ["addresses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shipping_method_id"], ["shipping_methods.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )

    op.drop_constraint(
        "order_lines_order_id_fkey", "order_lines", type_="foreignkey"
    )
    op.drop_table("shop_orders")
    op.create_foreign_key(
        None, "order_lines", "orders", ["order_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_lines", type_="foreignkey")
    op.create_foreign_key(
        "order_lines_order_id_fkey",
        "order_lines",
        "shop_orders",
        ["order_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_table(
        "shop_orders",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "order_date", sa.DATE(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "payment_method_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "shipping_address_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "shipping_method_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "order_total", sa.NUMERIC(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "order_status_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_status_id"],
            ["order_statuses.id"],
            name="shop_orders_order_status_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_method_id"],
            ["payment_methods.id"],
            name="shop_orders_payment_method_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipping_address_id"],
            ["addresses.id"],
            name="shop_orders_shipping_address_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shipping_method_id"],
            ["shipping_methods.id"],
            name="shop_orders_shipping_method_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="shop_orders_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="shop_orders_pkey"),
        sa.UniqueConstraint("id", name="shop_orders_id_key"),
    )
    op.drop_table("orders")
    # ### end Alembic commands ###
