"""Created User Review model

Revision ID: 7b46067d22b1
Revises: b2741ccf7568
Create Date: 2024-02-24 10:07:39.100273

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7b46067d22b1"
down_revision: Union[str, None] = "b2741ccf7568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_reviews",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "ordered_product_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("rating_value", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.CheckConstraint(
            "rating_value >= 1 and rating_value <= 5",
            name="check_rating_value_constraint",
        ),
        sa.ForeignKeyConstraint(
            ["ordered_product_id"], ["order_lines.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_reviews")
    # ### end Alembic commands ###
