"""Changed roles ondelete

Revision ID: 7d08a3f5cdbc
Revises: aef795690680
Create Date: 2024-01-14 12:57:45.578030

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7d08a3f5cdbc"
down_revision: Union[str, None] = "aef795690680"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        "users_role_id_fkey",
        "users",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(
        "users_role_id_fkey", "users", "roles", ["role_id"], ["id"]
    )
    # ### end Alembic commands ###
