"""Created product configuration model

Revision ID: 89f21471607f
Revises: aff1592fa34e
Create Date: 2024-02-18 11:06:20.460783

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "89f21471607f"
down_revision: Union[str, None] = "aff1592fa34e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_configurations",
        sa.Column(
            "product_item_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "variation_option_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_item_id"], ["product_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["variation_option_id"],
            ["variation_options.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_item_id", "variation_option_id"),
    )
    op.create_unique_constraint(None, "product_items", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_items", type_="unique")
    op.drop_table("product_configurations")
    # ### end Alembic commands ###
