"""Changed countries name

Revision ID: a834f25ee474
Revises: 7d08a3f5cdbc
Create Date: 2024-01-15 15:38:01.736049

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a834f25ee474"
down_revision: Union[str, None] = "7d08a3f5cdbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("countries_name_key", "countries", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("countries_name_key", "countries", ["name"])
    # ### end Alembic commands ###
