"""Changed the name of product configurations table

Revision ID: befe3ebaceee
Revises: 0fcb7605ee67
Create Date: 2024-03-05 11:44:07.279377

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "befe3ebaceee"
down_revision: Union[str, None] = "0fcb7605ee67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_product",
        sa.Column(
            "product_item_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column(
            "variation_option_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_item_id"], ["product_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["variation_option_id"],
            ["variation_options.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("product_item_id", "variation_option_id"),
    )
    op.drop_table("product_configurations")
    op.create_unique_constraint(None, "payment_methods", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment_methods", type_="unique")
    op.create_table(
        "product_configurations",
        sa.Column(
            "product_item_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "variation_option_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_item_id"],
            ["product_items.id"],
            name="product_configurations_product_item_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variation_option_id"],
            ["variation_options.id"],
            name="product_configurations_variation_option_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "product_item_id",
            "variation_option_id",
            name="product_configurations_pkey",
        ),
    )
    op.drop_table("configuration_product")
    # ### end Alembic commands ###
