"""Added default profile image to user

Revision ID: cdf01a3f71c4
Revises: cc3d883e4e2f
Create Date: 2024-02-24 16:04:48.856779

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cdf01a3f71c4"
down_revision: Union[str, None] = "cc3d883e4e2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_profiles", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_profiles", type_="unique")
    # ### end Alembic commands ###
