"""Added nullable false to fields

Revision ID: d6ebbc6512fe
Revises: 8ec4cb06abde
Create Date: 2024-01-12 14:49:02.404840

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d6ebbc6512fe"
down_revision: Union[str, None] = "8ec4cb06abde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
