"""Added relationships in all models

Revision ID: f7da4b592df6
Revises: fc4a1afc9f03
Create Date: 2024-01-21 12:27:37.533053

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f7da4b592df6"
down_revision: Union[str, None] = "fc4a1afc9f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column(
            "country_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
    )
    op.drop_constraint(
        "addresses_country_fkey", "addresses", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "addresses",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("addresses", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column("country", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_country_fkey",
        "addresses",
        "countries",
        ["country"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("addresses", "country_id")
    # ### end Alembic commands ###
