"""Added payment types

Revision ID: f8b3bcc031e9
Revises: 9155e775505a
Create Date: 2024-02-05 18:21:18.780348

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f8b3bcc031e9"
down_revision: Union[str, None] = "9155e775505a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_types",
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "addresses", ["id"])
    op.create_unique_constraint(None, "countries", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "countries", type_="unique")
    op.drop_constraint(None, "addresses", type_="unique")
    op.drop_table("payment_types")
    # ### end Alembic commands ###
