"""Added ondelete in addresses

Revision ID: fc4a1afc9f03
Revises: 55e2cdead4a5
Create Date: 2024-01-21 12:15:16.439451

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fc4a1afc9f03"
down_revision: Union[str, None] = "55e2cdead4a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "addresses_country_fkey", "addresses", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "addresses", "countries", ["country"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_country_fkey", "addresses", "countries", ["country"], ["id"]
    )
    # ### end Alembic commands ###
