from src.products.categories.responses import PRODUCT_CATEGORY_NOT_FOUND
from src.responses import (
    FORBIDDEN_RESPONSE,
    UNAUTHORIZED_RESPONSE,
    UNPROCESSABLE_ENTITY,
    VARIATION_NOT_FOUND,
)


UNAUTHORIZED_FORBIDDEN_CATEGORY_OR_VARIATION_NOT_FOUND_RESPONSE_UNPROCESSABLE_ENTITY = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_CATEGORY_NOT_FOUND,
    **VARIATION_NOT_FOUND,
    **UNPROCESSABLE_ENTITY,
}
