from src.products.items.responses import (
    PRODUCT_ITEM_NOT_FOUND,
    PRODUCT_ITEMS_NOT_FOUND,
)
from src.responses import (
    CART_NOT_FOUND_RESPONSE,
    FORBIDDEN_RESPONSE,
    SHOPPING_CART_ITEM_NOT_FOUND_RESPONSE,
    UNAUTHORIZED_RESPONSE,
)


UNAUTHORIZED_FORBIDDEN_PRODUCT_ITEM_OR_CART_NOT_FOUND_RESPONSE = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEM_NOT_FOUND,
    **CART_NOT_FOUND_RESPONSE,
}

UNAUTHORIZED_FORBIDDEN_PRODUCT_ITEMS_OR_CART_OR_SHOPPING_CART_ITEM_NOT_FOUND_RESPONSE = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEMS_NOT_FOUND,
    **CART_NOT_FOUND_RESPONSE,
    **SHOPPING_CART_ITEM_NOT_FOUND_RESPONSE,
}

UNAUTHORIZED_FORBIDDEN_PRODUCT_ITEMS_OR_CART_NOT_FOUND_RESPONSE = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEMS_NOT_FOUND,
    **CART_NOT_FOUND_RESPONSE,
}
