from src.responses import (
    FORBIDDEN_RESPONSE,
    UNAUTHORIZED_RESPONSE,
    UNPROCESSABLE_ENTITY,
    VARIATION_OPTION_NOT_FOUND,
)
from src.variations.responses import VARIATION_NOT_FOUND


UNAUTHORIZED_FORBIDDEN_VARIATION_OR_OPTION_NOT_FOUND_RESPONSE_UNPROCESSABLE_ENTITY = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **VARIATION_OPTION_NOT_FOUND,
    **VARIATION_NOT_FOUND,
    **UNPROCESSABLE_ENTITY,
}
