from src.products.items.responses import PRODUCT_ITEM_NOT_FOUND
from src.responses import (
    DELETED_RESPONSE,
    FORBIDDEN_RESPONSE,
    UNAUTHORIZED_RESPONSE,
    UNPROCESSABLE_ENTITY,
)
from src.variations.options.responses import VARIATION_OPTION_NOT_FOUND


PRODUCT_ITEM_OR_VARIATION_OPTION_NOT_FOUND_RESPONSE = {
    **PRODUCT_ITEM_NOT_FOUND,
    **VARIATION_OPTION_NOT_FOUND,
}

DELETED_UNAUTHORIZED_FORBIDDEN_PRODUCT_CONFIGURATION_NOT_FOUND_RESPONSE = {
    **DELETED_RESPONSE,
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEM_OR_VARIATION_OPTION_NOT_FOUND_RESPONSE,
}

UNAUTHORIZED_FORBIDDEN_PRODUCT_ITEM_OR_VARIATION_OPTION_NOT_FOUND_RESPONSE = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEM_OR_VARIATION_OPTION_NOT_FOUND_RESPONSE,
}

UNAUTHORIZED_FORBIDDEN_PRODUCT_ITEM_OR_VARIATION_OPTION_NOT_FOUND_RESPONSE_UNPROCESSABLE_ENTITY = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_ITEM_NOT_FOUND,
    **VARIATION_OPTION_NOT_FOUND,
    **UNPROCESSABLE_ENTITY,
}
