from datetime import datetime

from src.config import settings


users_data = [
    {
        "email": "ffriedman0@oakley.com",
        "hashed_password": settings.USER_PASSWORD,
        "first_name": "Fanechka",
        "last_name": "Friedman",
    },
    {
        "email": "tweatherby1@quantcast.com",
        "first_name": "Tasha",
        "last_name": "Weatherby",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "jglassup2@jiathis.com",
        "first_name": "Joane",
        "last_name": "Glassup",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "cpoor3@wiley.com",
        "first_name": "Carmelia",
        "last_name": "Poor",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "bnapoleone4@cdbaby.com",
        "first_name": "Bernard",
        "last_name": "Napoleone",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "gromaint5@economist.com",
        "first_name": "Ginelle",
        "last_name": "Romaint",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "vbarrim6@google.es",
        "first_name": "Valle",
        "last_name": "Barrim",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "kwingeat7@miitbeian.gov.cn",
        "first_name": "Katusha",
        "last_name": "Wingeat",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "ycastleton8@1und1.de",
        "first_name": "Yolane",
        "last_name": "Castleton",
        "hashed_password": settings.USER_PASSWORD,
    },
    {
        "email": "amingame9@bravesites.com",
        "first_name": "Ashley",
        "last_name": "Mingame",
        "hashed_password": settings.USER_PASSWORD,
    },
]

address_data = [
    {
        "unit_number": "28809",
        "street_number": "42981",
        "address_line1": "73 Magdeline Trail",
        "address_line2": "15th Floor",
        "city": "Mobile",
        "region": "Alabama",
        "postal_code": "36610",
    },
    {
        "unit_number": "292",
        "street_number": "1",
        "address_line1": "3344 Northland Terrace",
        "address_line2": "8th Floor",
        "city": "Louisville",
        "region": "Kentucky",
        "postal_code": "40205",
    },
    {
        "unit_number": "2284",
        "street_number": "1361",
        "address_line1": "82548 Butterfield Plaza",
        "address_line2": "Room 448",
        "city": "Saint Cloud",
        "region": "Minnesota",
        "postal_code": "56372",
    },
    {
        "unit_number": "95",
        "street_number": "8517",
        "address_line1": "6473 High Crossing Point",
        "address_line2": "Apt 1811",
        "city": "Green Bay",
        "region": "Wisconsin",
        "postal_code": "54305",
    },
    {
        "unit_number": "0",
        "street_number": "5",
        "address_line1": "310 Everett Plaza",
        "address_line2": "Apt 1156",
        "city": "Tampa",
        "region": "Florida",
        "postal_code": "33673",
    },
    {
        "unit_number": "38718",
        "street_number": "20474",
        "address_line1": "3 Anniversary Point",
        "address_line2": "11th Floor",
        "city": "Atlanta",
        "region": "Georgia",
        "postal_code": "30301",
    },
    {
        "unit_number": "3",
        "street_number": "62970",
        "address_line1": "08 Division Court",
        "address_line2": "Room 1942",
        "city": "Oklahoma City",
        "region": "Oklahoma",
        "postal_code": "73135",
    },
    {
        "unit_number": "8572",
        "street_number": "77476",
        "address_line1": "9433 Shasta Road",
        "address_line2": "13th Floor",
        "city": "Columbia",
        "region": "South Carolina",
        "postal_code": "29215",
    },
    {
        "unit_number": "7",
        "street_number": "6473",
        "address_line1": "17676 Stone Corner Park",
        "address_line2": "Suite 64",
        "city": "Roanoke",
        "region": "Virginia",
        "postal_code": "24004",
    },
    {
        "unit_number": "0",
        "street_number": "396",
        "address_line1": "0242 Wayridge Avenue",
        "address_line2": "Apt 1208",
        "city": "Detroit",
        "region": "Michigan",
        "postal_code": "48217",
    },
    {
        "unit_number": "05837",
        "street_number": "0698",
        "address_line1": "75690 Gerald Pass",
        "address_line2": "Apt 1082",
        "city": "Fresno",
        "region": "California",
        "postal_code": "93750",
    },
    {
        "unit_number": "9",
        "street_number": "03",
        "address_line1": "13782 Karstens Road",
        "address_line2": "Suite 80",
        "city": "Atlanta",
        "region": "Georgia",
        "postal_code": "31136",
    },
    {
        "unit_number": "9800",
        "street_number": "210",
        "address_line1": "606 Sloan Trail",
        "address_line2": "Room 491",
        "city": "Hampton",
        "region": "Virginia",
        "postal_code": "23668",
    },
    {
        "unit_number": "68628",
        "street_number": "727",
        "address_line1": "02 Loftsgordon Plaza",
        "address_line2": "Room 1444",
        "city": "Minneapolis",
        "region": "Minnesota",
        "postal_code": "55480",
    },
    {
        "unit_number": "29",
        "street_number": "42253",
        "address_line1": "51 Monica Circle",
        "address_line2": "1st Floor",
        "city": "New York City",
        "region": "New York",
        "postal_code": "10105",
    },
    {
        "unit_number": "7926",
        "street_number": "254",
        "address_line1": "846 7th Circle",
        "address_line2": "Apt 1619",
        "city": "El Paso",
        "region": "Texas",
        "postal_code": "79905",
    },
    {
        "unit_number": "3",
        "street_number": "00353",
        "address_line1": "49 Westend Center",
        "address_line2": "Suite 26",
        "city": "Brooklyn",
        "region": "New York",
        "postal_code": "11254",
    },
    {
        "unit_number": "281",
        "street_number": "3",
        "address_line1": "286 Doe Crossing Plaza",
        "address_line2": "Apt 1213",
        "city": "Torrance",
        "region": "California",
        "postal_code": "90510",
    },
    {
        "unit_number": "63",
        "street_number": "19449",
        "address_line1": "5 1st Court",
        "address_line2": "Suite 81",
        "city": "Columbia",
        "region": "South Carolina",
        "postal_code": "29203",
    },
    {
        "unit_number": "8",
        "street_number": "32",
        "address_line1": "5177 Milwaukee Street",
        "address_line2": "PO Box 77721",
        "city": "Newark",
        "region": "New Jersey",
        "postal_code": "07112",
    },
]

payment_methods_data = [
    {
        "provider": "Master Card",
        "account_number": "6837536537771158",
        "expiry_date": datetime(2024, 11, 5),
        "is_default": True,
    },
    {
        "provider": "Master Card",
        "account_number": "2239045303432029",
        "expiry_date": datetime(2025, 4, 6),
        "is_default": True,
    },
    {
        "provider": "Visa",
        "account_number": "5829373658136293",
        "expiry_date": datetime(2025, 6, 26),
        "is_default": True,
    },
    {
        "provider": "Visa",
        "account_number": "8541919801138361",
        "expiry_date": datetime(2025, 1, 11),
        "is_default": True,
    },
    {
        "provider": "Visa",
        "account_number": "2206178905378059",
        "expiry_date": datetime(2025, 5, 9),
        "is_default": True,
    },
    {
        "provider": "Master Card",
        "account_number": "9712864412586547",
        "expiry_date": datetime(2024, 11, 28),
        "is_default": True,
    },
    {
        "provider": "Visa",
        "account_number": "3166250367651548",
        "expiry_date": datetime(2025, 2, 24),
        "is_default": True,
    },
    {
        "provider": "Master Card",
        "account_number": "1098426077427530",
        "expiry_date": datetime(2025, 9, 28),
        "is_default": True,
    },
    {
        "provider": "Master Card",
        "account_number": "5783906991081809",
        "expiry_date": datetime(2025, 4, 14),
        "is_default": True,
    },
    {
        "provider": "Visa",
        "account_number": "3755517087203477",
        "expiry_date": datetime(2025, 6, 1),
        "is_default": True,
    },
]
