from src.config import settings


user_data = [
    {
        "email": "ffriedman0@oakley.com",
        "first_name": "Fanechka",
        "last_name": "Friedman",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "tweatherby1@quantcast.com",
        "first_name": "Tasha",
        "last_name": "Weatherby",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "jglassup2@jiathis.com",
        "first_name": "Joane",
        "last_name": "Glassup",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "cpoor3@wiley.com",
        "first_name": "Carmelia",
        "last_name": "Poor",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "bnapoleone4@cdbaby.com",
        "first_name": "Bernard",
        "last_name": "Napoleone",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "gromaint5@economist.com",
        "first_name": "Ginelle",
        "last_name": "Romaint",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "vbarrim6@google.es",
        "first_name": "Valle",
        "last_name": "Barrim",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "kwingeat7@miitbeian.gov.cn",
        "first_name": "Katusha",
        "last_name": "Wingeat",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "ycastleton8@1und1.de",
        "first_name": "Yolane",
        "last_name": "Castleton",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
    {
        "email": "amingame9@bravesites.com",
        "first_name": "Ashley",
        "last_name": "Mingame",
        "hashed_password": settings.USER_PASSWORD,
        "role_id": 1,
        "is_superuser": False,
    },
]
