from src.addresses.responses import ADDRESS_NOT_FOUND_RESPONSE
from src.payments.methods.response import PAYMENT_METHOD_NOT_FOUND_RESPONSE
from src.responses import (
    SHIPPING_METHOD_NOT_FOUND_RESPONSE,
    UNAUTHORIZED_RESPONSE,
    UNPROCESSABLE_ENTITY,
)


UNAUTHORIZED_PAYMENT_OR_SHIPPING_METHOD_ADDRESS_NOT_FOUND_UNPROCESSABLE_ENTITY_RESPONSE = {
    **UNAUTHORIZED_RESPONSE,
    **PAYMENT_METHOD_NOT_FOUND_RESPONSE,
    **SHIPPING_METHOD_NOT_FOUND_RESPONSE,
    **ADDRESS_NOT_FOUND_RESPONSE,
    **UNPROCESSABLE_ENTITY,
}
