from src.products.categories.responses import PRODUCT_CATEGORY_NOT_FOUND
from src.responses import (
    FORBIDDEN_RESPONSE,
    PRODUCT_NOT_FOUND,
    UNAUTHORIZED_RESPONSE,
    UNPROCESSABLE_ENTITY,
)


UNAUTHORIZED_FORBIDDEN_CATEGORY_OR_PRODUCT_NOT_FOUND_RESPONSE_UNPROCESSABLE_ENTITY = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_CATEGORY_NOT_FOUND,
    **PRODUCT_NOT_FOUND,
    **UNPROCESSABLE_ENTITY,
}

UNAUTHORIZED_FORBIDDEN_PRODUCT_CATEGORY_NOT_FOUND_RESPONSE_UNPROCESSABLE_ENTITY = {
    **UNAUTHORIZED_RESPONSE,
    **FORBIDDEN_RESPONSE,
    **PRODUCT_CATEGORY_NOT_FOUND,
    **UNPROCESSABLE_ENTITY,
}
